spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.6.77.105:3306/testtc_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: hj5JuX@uZ4b2Tupdkrs79PQ7
  cloud:
    nacos:
      discovery:
        server-addr: 10.6.77.105:8848
  application:
    name: testtc-order


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      #\u5168\u5C40\u7684\u903B\u8F91\u5220\u9664\u89C4\u5219
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8000
logging:
  level:
    com.test.tc.order: debug