spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.6.77.105:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
          - Query=url, baidu

        - id: product-route
          uri: lb://testtc-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: ware-route
          uri: lb://testtc-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: order-route
          uri: lb://testtc-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

  application:
    name: testtc-gateway
server:
  port: 88